# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
# #
# # Examples:
# #
# #   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
# #   Mayor.create(name: 'Emanuel', city: cities.first)

Video.create(title: "Pride & Prejudice", description: "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice? (129 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Romance", video_url: "https://www.youtube.com/watch?v=fJA27Jujzq4")
Video.create(title: "Once", description: "A modern-day musical about a busker and an immigrant and their eventful week in Dublin, as they write, rehearse and record songs that tell their love story. (85 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTEwNjExOTc2MTJeQTJeQWpwZ15BbWU3MDYzODQ3NDE@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Romance", video_url: "https://www.youtube.com/watch?v=726SFblz9Lk")
Video.create(title: "Groundhog Day", description: "A weatherman finds himself inexplicably living the same day over and over again. (101 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Romance", video_url: "https://www.youtube.com/watch?v=tSVeDx9fk60")

Video.create(title: "Starship Troopers", description: "Humans in a fascistic, militaristic future do battle with giant alien bugs in a fight for survival. (129 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BNThlOTFhOGEtZjE2NC00MzMzLThkYWItZjlkNWNlMDAzMGZkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1._SY209_CR6,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Fiction", video_url: "https://www.youtube.com/watch?v=Y07I_KER5fE")
Video.create(title: "Dredd", description: "In a violent, futuristic city where the police have the authority to act as judge, jury and executioner, a cop teams with a trainee to take down a gang that deals the reality-altering drug, SLO-MO. (95 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BODkyNDQzMzUzOF5BMl5BanBnXkFtZTcwODYyMDEyOA@@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Fiction", video_url: "https://www.youtube.com/watch?v=G-eI5oLlIeY")
Video.create(title: "The Matrix", description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. (136 mins.) ", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1._SX140_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Fiction", video_url: "https://www.youtube.com/watch?v=m8e-FF8MsqU")

Video.create(title: "Mad Max", description: "A woman rebels against a tyrannical ruler in postapocalyptic Australia in search for her home-land with the help of a group of female prisoners, a psychotic worshipper, and a drifter named Max. (120 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyMTE0ODcxNF5BMl5BanBnXkFtZTgwODE4NDQzNTE@._V1._SY209_CR2,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Action", video_url: "https://www.youtube.com/watch?v=hEJnMQG9ev8")
Video.create(title: "Logan", description: "In the near future, a weary Logan cares for an ailing Professor X, somewhere on the Mexican border. However, Logan's attempts to hide from the world, and his legacy, are upended when a young mutant arrives, pursued by dark forces. (137 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQwODQwNTg4OV5BMl5BanBnXkFtZTgwMTk4MTAzMjI@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Action", video_url: "https://www.youtube.com/watch?v=Div0iP65aZo")
Video.create(title: "Inception", description: "A thief, who steals corporate secrets through use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO. (148 mins.)", small_cover_url: "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1._SY209_CR0,0,140,209_.jpg", large_cover_url: "/tmp/monk_large.jpg", category: "Action", video_url: "https://www.youtube.com/watch?v=8hP9D6kZseM")


User.create(full_name: "Jia-Hung Lin", email: "pk60905@hotmail.com", password: "password", admin: true, token: SecureRandom.urlsafe_base64)